name: Run Assignment
on: [push, workflow_dispatch]

jobs:
  p2p-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Run Node Simulation
        run: python node_test.py
